apiVersion: v1
kind: Service
metadata:
  name: seedcamp-api
  namespace: default
  labels:
    app: seedcamp
    component: api
spec:
  type: LoadBalancer
  selector:
    app: seedcamp
    component: api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
