apiVersion: v1
kind: Service
metadata:
  name: adcamp-api
  namespace: adcamp
  labels:
    app: adcamp
    component: api
spec:
  type: LoadBalancer
  selector:
    app: adcamp
    component: api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
